---
galaxy_info:
  role_name: oradb_manage_users
  description: Ansible role to manage users
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  
  
dependencies: []
