---
galaxy_info:
  role_name: oraswgi_manage_patches
  description: Ansible role to manage GI patching
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
